### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by oninross** [google/emoji-scavenger-hunt#28]
So I am reusing the same codes from this repo for retraining.  It was all working for me for the past few days until now.  I received the issue below:

```
Traceback (most recent call last):
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1486, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1252, in main
    FLAGS.architecture))
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 549, in get_random_cached_bottlenecks
    image_dir, category)
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 254, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by oninross** [comment]
Somehow the issue is gone.  I dont know what I did.  But I did upgrade the Docker file script to get the latest version of the retrain.py.  Training went out smoothly, the models loaded properly, but I get this error when I try to predict

```
Uncaught (in promise) Error: Missing input placeholders: Placeholder
    at GraphExecutor.checkInput (graph_executor.js:253)
    at GraphExecutor.execute (graph_executor.js:134)
    at FrozenModel.execute (frozen_model.js:161)
    at mobilenet.js:49
    at Object.Tracking.tidy (tracking.js:36)
    at MobileNet.predict (mobilenet.js:36)
    at snap.js:69
    at Object.Tracking.tidy (tracking.js:36)
    at HTMLImageElement.self.PLANT.onload (snap.js:68)
```

**Comment by tushuhei** [comment]
Our script assumes the model input placeholder has the name `input` as specified below. https://github.com/google/emoji-scavenger-hunt/blob/c6dbb72a05c8c95669dacd047c17e75721403007/src/js/mobilenet.ts#L28
However, it looks like your model has renamed the input placeholder as `Placeholder` instead for some reason. Could you try editing the line above from `'input'` to `'Placeholder'` and running your model again?

**Comment by oninross** [comment]
Thank you @tushuhei, that worked perfectly! :)

**Comment by nidhishgandhi** [comment]
@oninross how did you upgrade docker files??I am getting same error what should i do..

![Capture](https://user-images.githubusercontent.com/62073952/85366714-8b243c00-b545-11ea-9b31-b0c7381a15e1.PNG)

**Comment by tushuhei** [comment]
Hi nidhishgandhi,

From seeing the error saying "Label yawning has no images in the category training", I assume it's caused by a lack of images for training. Could you check if there are multiple images under `data/images/yawning` directory? Please refer to https://github.com/google/emoji-scavenger-hunt#build-your-own-model for more details about data setup.
