### ISSUE TITLE
Error when creating bottlenecks

### ISSUE THREAD

**Issue by oninross** [google/emoji-scavenger-hunt#31]
For some reason, creating bottlenecks abruptly stops and returns this error:

```
INFO:tensorflow:Creating bottleneck at /tmp/bottleneck/asystasia/asystasia gangetica.jpg_mobilenet_1.0_224.txt
Traceback (most recent call last):
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1487, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1188, in main
    bottleneck_tensor, FLAGS.architecture)
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 500, in cache_bottlenecks
    resized_input_tensor, bottleneck_tensor, architecture)
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 438, in get_or_create_bottleneck
    if not os.path.exists(bottleneck_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 37: ordinal not in range(128)
```

What does it mean?

**Comment by jbruwer** [comment]
I'm not 100% sure what you're doing here without more context but from the looks of it it seems like the retrain script is parsing some character (é) which it can't handle. We are simply using the retrain script (@tushuhei can confirm) so I would check with tensorflow directly.

**Comment by oninross** [comment]
I'm just training a set of images.  It just so happens that by removing that folder solved it. It still would be nice to know what went wrong
